# Generated by Django 3.0.6 on 2020-05-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teavello', '0002_destination_prince'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='prince',
            new_name='prisce',
        ),
    ]
