# Generated by Django 3.0.6 on 2020-05-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teavello', '0003_auto_20200528_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='prisce',
            new_name='price',
        ),
    ]
